=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/reports.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT reports (report)+ >

<!ELEMENT report (description, reportparameters, reportheader, pageheader, detailreports?, calculations, levels) >
<!ATTLIST report
   id            CDATA  #REQUIRED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT pageheader (field*, switch*, if*) >
<!ATTLIST pageheader
>

<!ELEMENT reportheader (field*, switch*, if*) >
<!ATTLIST reportheader
>

<!ELEMENT levels (level)* >
<!ELEMENT level (header?, detail, footer?) >
<!ATTLIST level
	name CDATA #REQUIRED 
	identification CDATA #IMPLIED 
	condition CDATA #IMPLIED
>

<!ELEMENT header (field*, (switch*| if*)?) >
<!ELEMENT footer (field*, (switch*| if*)?) >

<!ATTLIST footer
	line (above_below|below|above|none) #IMPLIED
	space (above_below|below|above|none) #IMPLIED
>

<!ELEMENT field (value* | fielddetail*)>
	<!-- fielddetail only in reportheader and pageheader; is directly evaluated -->
<!ELEMENT fielddetail (switch | if | value*)>

<!ATTLIST fielddetail
	condition CDATA #IMPLIED
>	

<!ELEMENT caption (value)*>
<!ELEMENT shortcaption (value)*>

<!ATTLIST field
	whichfield CDATA #IMPLIED
	calculation CDATA #IMPLIED
	pos	CDATA #IMPLIED
	width CDATA #IMPLIED
	format CDATA #IMPLIED
	align (left|right|center) #IMPLIED
	line (above_below|below|above|none) #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
	condition CDATA #IMPLIED
	format CDATA #IMPLIED
	function CDATA #IMPLIED
	variable CDATA #IMPLIED
	text CDATA #IMPLIED
	calculation CDATA #IMPLIED
>

<!ELEMENT detail (switch | if | (lowerLevelReport*) |(field)*) >

<!ELEMENT switch (case*, default?)>
<!ELEMENT if ((lowerLevelReport|field*|value*),switch?) >
<!ELEMENT case ((lowerLevelReport*|field*|value*),switch?) >
<!ELEMENT default ((lowerLevelReport|field*|value*),switch?) >  
	<!-- value only inside reportHeader and pageHeader; 
		 lowerLevelReport only inside level
	-->

<!ATTLIST case
	condition CDATA #REQUIRED
>	

<!ATTLIST if
	condition CDATA #REQUIRED
>	

<!ELEMENT reportparameters (reportparameter)* >

<!ELEMENT reportparameter (option*) >
<!ATTLIST reportparameter
	name CDATA #REQUIRED
	comment CDATA #IMPLIED
	condition CDATA #IMPLIED
>

<!ELEMENT option EMPTY>
<!ATTLIST option
	name CDATA #REQUIRED
	condition CDATA #IMPLIED
	calculation CDATA #IMPLIED
>

<!ELEMENT calculations (calculation)+>
<!ELEMENT calculation (caption?, shortcaption?, template?, query)>
<!ATTLIST calculation 
	id CDATA #REQUIRED
	returnsFormat CDATA #REQUIRED
	returns CDATA #REQUIRED
	align (left|right|center) #IMPLIED
>

<!ELEMENT lowerLevelReport (parameter*)>
<!ATTLIST lowerLevelReport
	level CDATA #REQUIRED
	calculation CDATA #IMPLIED
	condition CDATA #IMPLIED
>

<!ELEMENT parameter (value)*>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!ELEMENT query (queryDetail)*>
<!ELEMENT queryDetail (value*, parameter*, switch*)>
<!ATTLIST queryDetail
	condition CDATA #IMPLIED
>

<!ELEMENT template (queryDetail*)>

<!ELEMENT detailreports (detailreport*)>
<!ELEMENT detailreport (parameter*,detailreportquery)>
<!ATTLIST detailreport
    id CDATA #REQUIRED
    action CDATA #REQUIRED
>

<!ELEMENT detailreportquery (#PCDATA)>

=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/template.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE reports SYSTEM "reports.dtd">
<reports>
	<report id="todo">
		<description>
			todo
		</description>
		<reportparameters>
			<reportparameter name="param_todo"/>
		</reportparameters>
		
		<reportheader/>
		<pageheader>
			<field whichfield="title1"><value text ="todo" /></field>
			<field whichfield="title2"><value text = "todo"/></field>
			<field whichfield="descr1"><value text = "todo"/></field>
			<field whichfield="period1"><value text = "todo"/></field>
			<field whichfield="period2"><value text = "todo"/></field>
			<field whichfield="descr2"><value text = "todo"/></field>
			<field whichfield="type"><value text = "todo"/></field>
			<field whichfield="left1"><value text = "todo"/></field>
			<field whichfield="left2"><value text = "todo"/></field>
		</pageheader>

		<calculations>
		
			<!-- template calculation for a row -->
			<calculation id="todo"
					returns="todo"
					returnsFormat="row">
				<query>
					<queryDetail><value>
					SELECT todo
					FROM todo
					WHERE todo
					</value></queryDetail>
				</query>
			</calculation>
			
			<!-- template calculation for a column -->
			<calculation id="todo" 
					returnsFormat="currency" returns="amount">
				<caption><value text="todo"/></caption>
				<query>
					<queryDetail><value function="todo({{param1}}, ...)"/>
					</queryDetail>                                          
				</query>
			</calculation>

		</calculations>

		<levels>		
		
			<!-- required: the main report level -->
			<level name="main">
				<detail>
					<lowerLevelReport level="todo">
					</lowerLevelReport>
				</detail>
			</level> <!-- main -->

			<!-- a level for grouping rows -->
			<level name="todo" identification="some variable">
				<header>
					<field whichfield="header 0" pos="0 cm" width="10cm">
							<value text="something "/>
							<value variable="somevariable"/>
					</field>
				</header>
				<detail>
					<lowerLevelReport level="todo2">
						<parameter name="param_something"/>
					</lowerLevelReport>
				</detail>
				<footer>
					<field whichfield="left 0" pos="0cm" width="5 cm">
						<value text="todo"/></field>
					<field whichfield="left 1" pos="0cm" width="5 cm">
						<value text = "todo"/></field>
					<field whichfield="columns" pos="indented" line="above_below">
						<value function="getIncMinusExp({{lineId}}, {{column}})"/>
					</field>
				</footer>
			</level><!-- todo -->
		
			<!-- a level with detailed data -->
			<level name="todo2" identification="line_something" condition="HasColumns">
				<detail>
					<field whichfield="left 0" pos="1 cm" width="1.5 cm"><value variable="line_something"/></field>
					<field whichfield="left 1" pos="2.5 cm" width="5 cm"><value variable="some text"/></field>
					<field calculation="calcualateSomething" whichfield="columns"></field>
				</detail>
			</level><!-- todo2 -->

		</levels>
	</report><!-- todo -->
	
</reports>

=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/FinancialDevelopment/topdonorreport.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE reports SYSTEM "../reports.dtd">
<reports>
	<report id="TopDonorReport">
		<description>
			This report considers gifts given between the two specified dates, and can include all gifts or, if
			selected, those to a particular motivation, motivation detail or recipient. For the defined set of gifts
			and its total value, the donors are sorted into a list, starting with those who gave most, and showing
			the percentage that their gifts contributed to the total received (for this motivation or recipient, if
			specified) and the cumulative percentage, moving down the list starting with the top donor.
		</description>
		<reportparameters>
			<reportparameter name="param_ledger_number_i"/>
			<reportparameter name="param_currency"/>
			<reportparameter name="param_start_date"/>
			<reportparameter name="param_end_date"/> 
			<reportparameter name="param_minimum_amount"/>
		</reportparameters>
		
		<reportheader/>
		<pageheader>
			<field whichfield="title1"><value text ="Top Donor Report" /></field>
			<field whichfield="title2"><value function="getLedgerName({{param_ledger_number_i}})"/></field>
			<field whichfield="descr1">
				<value text="Ledger "/>
				<value variable="param_ledger_number_i"/>
				<value text="   "/>
				<value function="getLedgerName({{param_ledger_number_i}})"/>
			</field>
			<field whichfield="descr2">
				<fielddetail condition="eq({param_donor_type}, top)">
					<value text="Top "/>
					<value variable="param_percentage"/>
					<value text="%"/>
				</fielddetail>
				<fielddetail condition="eq({param_donor_type}, middle)">
					<value text="From "/>
					<value variable="param_percentage"/>
					<value text="% To "/>
					<value variable="param_to_percentage"/>
					<value text="%"/>
				</fielddetail>
				<fielddetail condition="eq({param_donor_type}, bottom)">
					<value text="Bottom "/>
					<value variable="param_bottom_percentage"/>
					<value text="%"/>
				</fielddetail>
			</field>
			<field whichfield="descr3">
				<fielddetail condition="eq({param_recipientkey}, 0)">
					<value text="All recipients;   "/>
				</fielddetail>
				<fielddetail condition="not(eq({param_recipientkey}, 0))">
					<value text="Recipient: "/>
					<value function="getPartnerShortName({param_recipientkey})"/>
					<value text=";   "/>
				</fielddetail>
				<fielddetail condition="eq({param_all_partners}, true)">
					<value text="All Donors"/>
				</fielddetail>
				<fielddetail condition="eq({param_extract}, true)">
					<value text="Donors from extract: "/>
					<value variable="param_extract_name"/>
				</fielddetail>
			</field>
			
			<field whichfield="period1">
				<fielddetail>
					<value text="Period:  "/>
					<value variable="param_start_date" format="formatteddate"/>
					<value text=" To "/>
					<value variable="param_end_date" format="formatteddate"/>
				</fielddetail>
			</field>
			<field whichfield="period2">
				<value text="Motivation (Group,Detail): "/>
                <value variable="param_group_detail_desc"></value>
			</field>
			<field whichfield="period3">
				<value text="Currency: "/>
				<value function="getCurrency({{param_ledger_number_i}}, {GLOBAL:param_currency})"/>
			</field>
			
		</pageheader>

		<calculations>
			
			<calculation id="GetTotalAmount" returns="TotalAmount" returnsFormat="row">
				<query>
					<queryDetail>
						<value>
						SELECT 
						</value>
					</queryDetail>
					<queryDetail condition="eq({param_currency}, Base)">
						<value>
							SUM(detail.a_gift_amount_n) AS TotalAmount
						 </value>
					</queryDetail>
					<queryDetail condition="eq({param_currency}, International)">
						<value>
							SUM(detail.a_gift_amount_intl_n) AS TotalAmount
						 </value>
					</queryDetail>
					<queryDetail>
						<value>
						FROM
							 PUB_a_gift as gift, 
							 PUB_a_gift_detail as detail,
							 PUB_a_gift_batch
						 </value>
					</queryDetail>
					<queryDetail condition="eq({param_extract}, true)">
						<value>
							, PUB_m_extract,
							PUB_m_extract_master
						WHERE 
							gift.p_donor_key_n = PUB_m_extract.p_partner_key_n
							AND PUB_m_extract.m_extract_id_i = PUB_m_extract_master.m_extract_id_i
							AND PUB_m_extract_master.m_extract_name_c = {param_extract_name}
							AND
						</value>
					</queryDetail>
					<queryDetail condition="eq({param_all_partners}, true)">
						<value>
						WHERE
						</value>
					</queryDetail>
					<queryDetail>
						<value>
								detail.a_ledger_number_i = gift.a_ledger_number_i
							AND detail.a_batch_number_i = gift.a_batch_number_i
							AND detail.a_gift_transaction_number_i = gift.a_gift_transaction_number_i
							AND gift.a_date_entered_d BETWEEN {#param_start_date#} AND {#param_end_date#}
							AND gift.a_ledger_number_i ={{param_ledger_number_i}}
							AND PUB_a_gift_batch.a_ledger_number_i = {{param_ledger_number_i}}
							AND PUB_a_gift_batch.a_batch_number_i = gift.a_batch_number_i
							AND ( PUB_a_gift_batch.a_batch_status_c = 'Posted' OR
								  PUB_a_gift_batch.a_batch_status_c = 'posted')
						</value>
					</queryDetail>
					<queryDetail condition="not(eq({param_recipientkey}, 0))">
						<value>
							AND detail.p_recipient_key_n = {{param_recipientkey}}
						</value>
					</queryDetail>
					<queryDetail condition="eq({param_all_motivation_groups}, false)">
                        <value>
                            AND detail.a_motivation_group_code_c IN ({{param_motivation_group_quotes}})
                        </value>
                    </queryDetail>
                    <queryDetail condition="eq({param_all_motivation_details}, false)">
                        <value>
                            AND (detail.a_motivation_group_code_c,detail.a_motivation_detail_code_c) IN ({{param_motivation_group_detail_pairs}})
                        </value>
                    </queryDetail>
				</query>
			</calculation>
			
			<calculation id="MakeTopDonor" returns="automatic" returnsFormat="row">
				<query>
					<queryDetail>
						<value text="NO-SQL"/>
						<value function="MakeTopDonor({TotalAmount}, {param_percentage}, {param_to_percentage}, 
							{param_extract}, {param_extract_name}, {param_start_date}, {param_end_date},
							{param_recipientkey}, {param_motivation_group_quotes}, {param_motivation_group_detail_pairs})"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="Donor Key" 
					returnsFormat="partnerkey" returns="text">
				<caption><value text="Donor Key"/></caption>
				<query>
					<queryDetail><value variable="DonorKey"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="Donor Name" 
					returnsFormat="text" returns="text">
				<caption><value text="Donor Name"/></caption>
				<query>
					<queryDetail><value variable="ShortName"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="Partner Class" 
					returnsFormat="text" returns="text">
				<caption><value text="Partner Class"/></caption>
				<query>
					<queryDetail><value variable="PartnerClass"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="Total Gifts" returnsFormat="currency" returns="amount">
				<caption><value text="Total Gifts"/></caption>
				<query>
					<queryDetail><value variable="Amount"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="%of Total" 
					returnsFormat="-#,##0.00;#,##0.00; ; ;" returns="text">
				<caption><value text="%of Total"/></caption>
				<query>
					<queryDetail><value variable="TotalPercent"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="Cumulative %" 
					returnsFormat="-#,##0.00;#,##0.00" returns="text">
				<caption><value text="Cumulative %"/></caption>
				<query>
					<queryDetail><value variable="CumulativePercent"/>
					</queryDetail>                                          
				</query>
			</calculation>
			<calculation id="Address" 
					returnsFormat="text" returns="text">
				<caption><value text="Address"/></caption>
				<query>
					<queryDetail><value variable="Address"/>
					</queryDetail>                                          
				</query>
			</calculation>
			
		</calculations>

		<levels>		
			<level name="main">
				<detail>
					<lowerLevelReport level="DonorLevel" calculation="GetTotalAmount"></lowerLevelReport>
				</detail>
			</level>
			
			<level name="DonorLevel">
				<detail>
					<field whichfield="columns" calculation="MakeTopDonor"/>
				</detail>
			</level>
		</levels>
		
	</report><!-- Donor Report -->
</reports>

=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/Personnel/unithierarchy.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE reports SYSTEM "../reports.dtd">           
<reports>
	<report id="Unit Hierarchy Report">
		<description>
			
		</description>
		<reportparameters>
			
			<!-- Below comma separated list of the column names. Not done! -->
			<reportparameter name="param_sortby_readable"/>
		</reportparameters>
		<reportheader/>

		<pageheader>
			<field whichfield="title1"><value text ="Unit Hierarchy" /></field>
			<field whichfield="title2"><value function = "getSiteName()"/></field>
   			<field whichfield="descr2">
			</field>
			<field whichfield="period1">
			</field>
			<field whichfield="descr1">
				<fielddetail>
					<value text="Base Unit: "/>
					<value variable="param_txtUnitCode"/>
				</fielddetail>
			</field>
			
		</pageheader>

		<calculations>
		
			<calculation id="UnitName" returnsFormat="text" returns="text">
				<caption><value text="Name"/></caption>
				<query>
					<queryDetail>
						<value variable="UnitName"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="UnitType" returnsFormat="text" returns="text">
				<caption><value text="Unit Type"/></caption>
				<query>
					<queryDetail>
						<value variable="Unit Type" format="text"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="UnitKey" returnsFormat="text" returns="text">
				<caption><value text="Key"/></caption>
				<query>
					<queryDetail>
						<value variable="UnitKey"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="PartnerKey" returnsFormat="partnerkey" returns="text">
				<query>
					<queryDetail>
						<value variable="PartnerKey"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="Parent Key" returnsFormat="partnerkey" returns="text">
				<query>
					<queryDetail>
						<value variable="param_txtUnitCode"/>
					</queryDetail>
				</query>
			</calculation>
			
			<calculation id="GetChildUnits" returns="UnitKey" returnsFormat="internal">
				<query>
					<queryDetail>
						<value text="NO-SQL"/>
						<value function="GenerateUnitHierarchy({param_txtUnitCode}, {param_chkInclude})"/>
					</queryDetail>
				</query>
			</calculation>
		
		</calculations>
		
		<levels>
			<level name="main">
				<detail>
					<lowerLevelReport level="ChildUnitLevel" calculation="GetChildUnits">
					</lowerLevelReport>
				</detail>
			</level> <!-- main -->

			<level name="ChildUnitLevel">
				<detail>
					<field whichfield="columns"/>
				</detail>
			</level>
		
		</levels>

	</report>

</reports>

=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/Personnel/generalshorttermerreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reports SYSTEM "../reports.dtd" >
<reports>

  <report id="Short Termer Report">
	<description>
		General Short termer report.
		Used for applications and other infos.
	</description>
	<reportparameters/>
	
    <reportheader></reportheader>
    <pageheader>
      <field whichfield="title1"><value text="Applicant General Info Report"></value></field>
      <field whichfield="title2"><value function="getSiteName()"></value></field>
      <field whichfield="descr1">
        <value text="Sorted by: "></value>
        <value variable="param_sortby_readable"></value>
      </field>
	  
      <field whichfield="period1">
        <fielddetail>
	  <value text="Application Status:"></value>
	</fielddetail>
	<fielddetail condition="eq({param_application_status_accepted}, true)">
	  <value text=" Accepted"></value>
	</fielddetail>
	<fielddetail condition="eq({param_application_status_cancelled}, true)">
	  <value text=" Cancelled"></value>
	</fielddetail>
	<fielddetail condition="eq({param_application_status_rejected}, true)">
	  <value text=" Rejected"></value>
	</fielddetail>
	<fielddetail condition="eq({param_application_status_enquiry}, true)">
	  <value text=" Enquiry"></value>
	</fielddetail>
	<fielddetail condition="eq({param_application_status_hold}, true)">
	  <value text=" Hold"></value>
	</fielddetail>
      </field>
	  
      <field whichfield="period2">
        <fielddetail>
          <value text="Selection: "></value>
        </fielddetail>
        <fielddetail condition="eq({param_source}, Event)">
          <value text="Event: "></value><value variable="param_event_code"></value>
        </fielddetail>
        <fielddetail condition="eq({param_source}, Extract)">
          <value text="Extract: "></value><value variable="param_extract_name"></value>
        </fielddetail>
        <fielddetail condition="eq({param_source},EntireDatabase)">
          <value text="Entire Database"></value>
        </fielddetail>
      </field>
    </pageheader>

    <calculations>
	
	<calculation align="left" id="Telephone" returns="text" returnsFormat="text">
		<caption><value text="Telephone"></value></caption>
		<query>
			<queryDetail>
				<value variable="Telephone"></value>
			</queryDetail>
		</query>
	</calculation>
	
    </calculations>
    
    <levels> 
	<level name="main">
		<detail>
			<switch>
				<case condition="eq({param_print_two_lines}, true)">
					<lowerLevelReport calculation="Select Partners" level="Partner Details 2 Lines"></lowerLevelReport>
				</case>
				<default>
					<lowerLevelReport calculation="Select Partners" level="Partner Details"></lowerLevelReport>
				</default>
			</switch>
		</detail>
	</level> 

	<level name="Partner Details" identification="PartnerKey">
		<detail>
			<field whichfield="Columns" calculation="CleanUp" ></field>
		</detail>
	</level>
	
	<level name="Partner Details 2 Lines" identification="PartnerKey">
		<header>
			<field whichfield="header 0" pos="0cm" width="7cm" calculation="MakePartnerName">
				<value text=""/>
				<value variable="PartnerNameAndKey"/>
			</field>
			<field whichfield="header 1" pos="7cm" width="10cm" calculation="MakePartnerName">
				<value text="Event: "/>
				<value variable="EventCode"/>
			</field>
		</header>
		<detail>
			<lowerLevelReport level="Only Data Level"></lowerLevelReport>
		</detail>
		<footer space="above">
		</footer>
	</level>
	
	<level name="Only Data Level" identification="PartnerKey">
		<detail>
			<field whichfield="Columns" calculation="CleanUp" ></field>
		</detail>
	</level>
	
    </levels>

  </report>
  
</reports>

=== OSGCorp/Sagetech-AI-Demo/openpetra-master/XmlReports/Finance/totalgivingforrecipients.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE reports SYSTEM "../reports.dtd">
<reports>
  <report id="TotalGivingForRecipients">
    <description>
      This report shows the total giving for each of the last 4 years for some fields and/or for various special
      types set up in the Partner module
    </description>
    <reportparameters>
      <reportparameter name="param_ledger_number_i"/>
      <reportparameter name="param_currency"/>
    </reportparameters>

    <reportheader/>
    <pageheader>
      <field whichfield="title1">
        <value text="Historic Donors Per Recipient" />
      </field>

      <field whichfield="title2">
        <value function="getLedgerName({{param_ledger_number_i}})"/>
      </field>
      <field whichfield="descr1">
        <value text="Ledger: "/>
        <value variable="param_ledger_number_i"/>
        <value text="   "/>
        <value function="getLedgerName({{param_ledger_number_i}})"/>
      </field>
      <field whichfield="descr2">
        <fielddetail condition="eq({param_recipient}, All Recipients)">
          <value text="All Donors"/>
        </fielddetail>
        <fielddetail condition="eq({param_recipient}, One Recipient)">
          <value text="One Recipient: "/>
          <value variable="param_recipient_key"/>
        </fielddetail>
        <fielddetail condition="eq({param_recipient}, Extract)">
          <value text="Recipients from Extract: "/>
          <value variable="param_extract_name"/>
        </fielddetail>
      </field>
      <field whichfield="period1">
        <value text="Currency: "/>
        <value function="getCurrency({{param_ledger_number_i}}, {GLOBAL:param_currency})"/>
      </field>
      <field whichfield="period2">
        <fielddetail condition="eq({param_field_selection}, all_fields)">
          <value text="Fields: All Fields"/>
        </fielddetail>
        <fielddetail condition="eq({param_field_selection}, selected_fields)">
          <value text="Selected Fields: "/>
          <value variable="param_clbFields"/>
        </fielddetail>
      </field>
      <field whichfield="period3">
        <fielddetail condition="eq({param_type_selection}, all_types)">
          <value text="Recipient Types: All Types"/>
        </fielddetail>
        <fielddetail condition="eq({param_type_selection}, selected_types)">
          <value text="Selected Types: "/>
          <value variable="param_clbTypes"/>
        </fielddetail>
      </field>

    </pageheader>

    <calculations>

      <calculation id="SelectRecipients" returns="automatic" returnsFormat="row">
        <query>
          <queryDetail>
            <value>Ict.Petra.Server.MFinance.queries.QueryFinanceReport.SelectGiftRecipients</value>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="SelectDonors" returns="automatic" returnsFormat="row">
        <query>
          <queryDetail>
            <value>Ict.Petra.Server.MFinance.queries.QueryFinanceReport.SelectGiftDonors</value>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="PartnerKey" returnsFormat="partnerkey" returns="text">
        <caption><value text="Donor Key"/></caption>
        <query>
          <queryDetail><value variable="DonorKey"/>
          </queryDetail>                                          
        </query>
      </calculation>

      <calculation id="DonorName" returnsFormat="text" returns="text">
        <caption>
          <value text="Donor Name"/>
        </caption>
        <query>
          <queryDetail>
            <value variable="DonorName"/>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="DonorClass" returnsFormat="text" returns="text">
        <caption>
          <value text="Class"/>
        </caption>
        <query>
          <queryDetail>
            <value variable="DonorClass"/>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="Recipient Key" returnsFormat="partnerkey" returns="text">
        <caption>
          <value text="Recipient Key"/>
        </caption>
        <query>
          <queryDetail>
            <value variable="RecipientKey"/>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="Recipient Name" returnsFormat="text" returns="text">
        <caption>
          <value text="Recipient Name"/>
        </caption>
        <query>
          <queryDetail>
            <value variable="RecipientName"/>
          </queryDetail>
        </query>
      </calculation>

      <calculation id="Year-0" returnsFormat="currency" returns="amount">
        <caption>
          <value variable="Year0"/>
        </caption>
        <query>
        </query>
      </calculation>

      <calculation id="Year-1" returnsFormat="currency" returns="amount">
        <caption>
          <value variable="Year1"/>
        </caption>
        <query>
        </query>
      </calculation>

      <calculation id="Year-2" returnsFormat="currency" returns="amount">
        <caption>
          <value variable="Year2"/>
        </caption>
        <query>
        </query>
      </calculation>

      <calculation id="Year-3" returnsFormat="currency" returns="amount">
        <caption>
          <value variable="Year3"/>
        </caption>
        <query>
        </query>
      </calculation>

    </calculations>

    <levels>
      <level name="main">
        <detail>
          <lowerLevelReport level="RecipientLevel" calculation="SelectRecipients"></lowerLevelReport>
        </detail>
      </level>

      <level name="RecipientLevel" identification="RecipientKey">
        <header>
          <field whichfield="header 1" pos="0cm" width="8cm">
            <value text="Recipient: "/>
            <value variable="RecipientKey" format="partnerKey"/>
            <value text="   "/>
            <value variable="RecipientName"/>
          </field>
        </header>
        <detail>
          <lowerLevelReport level="YearLevel" calculation="SelectDonors"></lowerLevelReport>
        </detail>
        <footer line="below" space="below">
          <field whichfield="column 3" line="above">
            <value function="getSumLowerReport({{lineId}}, 3)"/>
          </field>
          <field whichfield="column 4" line="above">
            <value function="getSumLowerReport({{lineId}}, 4)"/>
          </field>
          <field whichfield="column 5" line="above">
            <value function="getSumLowerReport({{lineId}}, 5)"/>
          </field>
          <field whichfield="column 6" line="above">
            <value function="getSumLowerReport({{lineId}}, 6)"/>
          </field>
        </footer>
      </level>

      <level name="YearLevel">
        <detail>
          <field whichfield="column 0" pos="0cm">
            <value variable="DonorKey" />
          </field>
          <field whichfield="column 1">
            <value variable="DonorName" />
          </field>
          <field whichfield="column 2">
            <value variable="DonorClass" />
          </field>
          <field whichfield="column 3">
            <value variable="YearTotal0" />
          </field>
          <field whichfield="column 4">
            <value variable="YearTotal1" />
          </field>
          <field whichfield="column 5">
            <value variable="YearTotal2" />
          </field>
          <field whichfield="column 6">
            <value variable="YearTotal3" />
          </field>
        </detail>
      </level>

    </levels>
  </report>
</reports>
